### ISSUE TITLE
Issue when using sum_run over time series where number of rows matches index

### ISSUE THREAD

**Issue by joshua-ghezzi** [gogonzo/runner#31]
Hi there, I've encountered an issue where sum_run does not work correctly on a time series when k equals the number of rows exactly. I'm using this code: 
mutate(`4WkSumHours` = sum_run(`Hours`, k = 28, idx = `PeriodEndDate`)) where k is the number of days to look back, idx is a column containing date objects and hours is a column containing numeric values. The window sum works excellently in all other cases where k does not equal the number of rows and only sums together hours from rows with periodenddate that is within 28 days before the current row periodenddate.

Here's a sample of output showing expected behaviour with 34 rows of data vs incorrect behaviour with 28 rows of data
[windowSum.xlsx](https://github.com/gogonzo/runner/files/3806739/windowSum.xlsx)

**Comment by gogonzo** [comment]
Hi @stratodash , thanks a lot for feedback. I've reproduced your output. The problem has been already resolved with actual CRAN release - a lot has been [improved](https://gogonzo.github.io/runner/news/index.html) in last month. Please update and I hope current release will be without surprises - if it would, don't hesitate to report an issue - thanks! 

Here examples to reproduce

### v0.2.0 with BUG
```r
devtools::install_version("runner", version = "0.2.0", repos = "http://cran.us.r-project.org")
library(runner)
library(dplyr)
library(openxlsx)
df <- read.xlsx("https://github.com/gogonzo/runner/files/3807650/window_sum_issue.xlsx") %>% 
  mutate(PeriodEndDate = as.Date(PeriodEndDate, origin = "1899-12-30"))

### 28 rows
df %>%
  filter(!is.na(incorrect)) %>% 
  mutate(calc = sum_run(Hours, k = 28, idx = PeriodEndDate))

# 34 rows
df %>%
  mutate(calc = sum_run(Hours, k = 28, idx = PeriodEndDate))
```

### current version (v0.2.3) without BUG
```r
install.packages("runner")
library(runner)
library(dplyr)
library(openxlsx)
df <- read.xlsx("https://github.com/gogonzo/runner/files/3807650/window_sum_issue.xlsx") %>% 
  mutate(PeriodEndDate = as.Date(PeriodEndDate, origin = "1899-12-30"))

### 28 rows
df %>%
  filter(!is.na(incorrect)) %>% 
  mutate(calc = sum_run(Hours, k = 28, idx = PeriodEndDate))

# 34 rows
df %>%
  mutate(calc = sum_run(Hours, k = 28, idx = PeriodEndDate))
```



[window_sum_issue.xlsx](https://github.com/gogonzo/runner/files/3807650/window_sum_issue.xlsx)
