### ISSUE TITLE
add more general support for irregularly spaced data

### ISSUE THREAD

**Issue by Raoul-Kima** [gogonzo/runner#32]
The following was written based on the documentation, not on actually testing the package.

First of all I think it's great that someone creates a general purpose package for running functions. A key part of the R data wrangling ecosystem that, as fas as I know, has been missing for a long time. I certainly missed it on many occations.

Currently this package provides support for regularly spaced time series (or other regularly spaced data) by assuming that the index of the datapoint corresponds to its position in time/space/whatever.
It also provides support for irregularly spaced data, by using a second input variable that explicitly defines the position of each datapoint. This (I assume) also means support for e.g. time series where there is more than one measurement per point im time.
This latter system is however at the moment restricted to cases where time/space/whatever is measured either as date object or as integer variable. It would be great if floating point values could also be used.
One could then also have a second variable of the same type that specifies "where" the windowed function should be computed. For example one could input a number of irregularly spaced temperature measurements and then use "mean" as running function and define regularly spaced points as "where" this function should be computed. The output then would be a regularly spaced time series of average temperatures.

**Comment by gogonzo** [comment]
Hi, thanks for feedback!

> This (I assume) also means support for e.g. time series where there is more than one measurement per point im time.

Yes, there can be multiple `x` elements per one `idx`

> This latter system is however at the moment restricted to cases where time/space/whatever is measured either as date object or as integer variable. It would be great if floating point values could also be used.

Reasonable point with allow `float` in `idx` argument - I've just created an issue, so I will work on this #33 

> One could then also have a second variable of the same type that specifies "where" the windowed function should be computed. For example one could input a number of irregularly spaced temperature measurements and then use "mean" as running function and define regularly spaced points as "where" this function should be computed. The output then would be a regularly spaced time series of average temperatures.

I'm not sure about this paragraph, don't get it. Could you elaborate on this please?

**Comment by Raoul-Kima** [comment]
> > One could then also have a second variable of the same type that specifies "where" the windowed function should be computed. For example one could input a number of irregularly spaced temperature measurements and then use "mean" as running function and define regularly spaced points as "where" this function should be computed. The output then would be a regularly spaced time series of average temperatures.
> 
> I'm not sure about this paragraph, don't get it. Could you elaborate on this please?

For a regular datasets (e.g. a time series sampled each second) there is a natural interval at which to compute the running function (e.g. once each second). For irregularly spaced data there isn't. One could of course assume that the user wants to compute the function once at each datapoint in the dataset, but this is not necessarily true. Therefore it would be helpful to add a wayto specify the places where the running function is computed (that is independend of the other input data). This, in principle, also includes the possibility to place the window in a place where there aren't actually any datapoints.

In the example in the previous post this is used to create a regular dataset of smoothed measurements out of an irregular set of raw measurements.

I hope this explanation is more understandable. If not, feel free to continue asking.

**Comment by gogonzo** [comment]
Ok, thanks for detailed explanation. Now I understand, and I like the idea. For example, one can have irregular ts, and can compute 7-day average for each sunday (even if sundays are missing in data). Sundays (dates or whatever) goes to `what = <vector of sundays>` and `idx = <dates from data>`.

Problem right now is that output is different than size of `x` because it will depend on `what` - I need to rethink this and approach package in different way. I will put this to the backlog, and will back to this in some time.

Thanks for ideas!

#34

**Comment by gogonzo** [comment]
`at` argument available in `runner` function on `master` branch. I will write relevant content in documentation page soon.

**Comment by gogonzo** [comment]
`idx` as numeric not trivial at this point, I will try to fix it later. Thanks

**Comment by gogonzo** [comment]
closing some implemented in #33 while #34 is not on the scope at this moment.
