### ISSUE TITLE
Running which function name

### ISSUE THREAD

**Issue by dchiu911** [gogonzo/runner#35]
Hi @gogonzo is `whicht_run()` from v0.2.0 now equivalent to `which_run()`?

**Comment by gogonzo** [comment]
Hi @dchiu911 , yes Sir. `whicht_run` is now just `which_run`, and `whichd_run` doesn't exist anymore. `whichd_run` can be replicated with `runner(x, f = function(x) which(x != lag(x)))`. Sorry for confusion, my bad, I forgot to deprocate these functions first. 
Thanks for reaching me out, I hope you are fine with the changes. If anything else, don't hesitate to create issues.

**Comment by dchiu911** [comment]
Thanks for the clarification! Btw, your example to replicate the deprecated `whichd_run()` doesn't seem to work:
``` r
library(runner)
set.seed(11)
x1 <- sample(c(TRUE, FALSE), 15, replace = TRUE)
which_run(x1)
#>  [1]  1  2  2  4  5  5  7  8  8 10 11 12 12 12 12
runner(x1, f = function(x) which(x != lag(x)))
#> Error in runner(x1, f = function(x) which(x != lag(x))): Expecting a single value: [extent=0].
```

<sup>Created on 2019-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gogonzo** [comment]
Hi, sorry have not checked example - below working one. What might be important is that `runner::runnner` accepts `f = function` which returns one element numeric (something alike `vapply`) - in the next release one could specify type of the output (like in `vapply`).

```r
library(runner)
set.seed(11)
x1 <- sample(c(TRUE, FALSE), 15, replace = TRUE)
 
# which = "first"
runner(x1, f = function(x) {
   which(x != dplyr::lag(x))[1]
})
# [1] NA NA  3  3  3  3  3  3  3  3  3  3  3  3  3
 
# which = "last
runner(x1, f = function(x) {
   dplyr::last(which(x != dplyr::lag(x)))
})
# [1] NA NA  3  4  4  6  7  7  9 10 10 10 13 13 13
```
