### ISSUE TITLE
Version with parallel execution not in CRAN?

### ISSUE THREAD

**Issue by gonzalezsieira** [gogonzo/runner#67]
Hello there! I took a look to the README and #57, and it seems that this cool feature is already available, but [latest version in CRAN](https://cran.r-project.org/package=runner) is 0.3.7.  I was wondering CRAN is outdated, or if this version was not finally released?.

Thanks for your work.

**Comment by gogonzo** [comment]
Hi @gonzalezsieira ,
thank you for your feedback! 
CRAN release will be done anytime soon, whenever I'll resolve some automation issues. It should be published this week. I'll comment on this issue if 0.3.8 will be released

**Comment by gonzalezsieira** [comment]
Thanks so much for your help! Looking forward to this new version :)

**Comment by gogonzo** [comment]
@gonzalezsieira runner 0.3.8 is on cran https://cran.r-project.org/web/packages/runner/index.html

Let me know if you find any problems with parallel processing. Enjoy!
