### ISSUE TITLE
Error in sys.call(-runner_call_idx)

### ISSUE THREAD

**Issue by tomoosting** [gogonzo/runner#72]
I've been getting the following error message:
Error in sys.call(-runner_call_idx) : invalid 'which' argument

5. sys.call(-runner_call_idx)
4. get_runner_call_arg_names()
3. set_from_attribute_difftime(x, k)
2. runner.data.frame(x, lag = "1 months", k = "4 months", idx = x$date, f = function(x) { cor(x$a, x$b) })
1. runner::runner(x, lag = "1 months", k = "4 months", idx = x$date, f = function(x) { cor(x$a, x$b) })

I've checked if it had something to do with my code but I get the same error message when running the following code from the tutorial:

x <- data.frame(
  date = seq.Date(Sys.Date(), Sys.Date() + 365, length.out = 20),
  a = rnorm(20),
  b = rnorm(20)
)

runner::runner(
  x, 
  lag = "1 months",
  k = "4 months", 
  idx = x$date, 
  f = function(x) {
    cor(x$a, x$b)
  }
)

Any help on how to solve this is much appreciated :)

**Comment by gogonzo** [comment]
Hi @tomoosting thank you for reporting this!
I'll fix that bug soon on CRAN soon, but before I make a release please use `library(runner)`.

**Comment by tomoosting** [comment]
Awesome, thanks for the quick reply.
I had no idea there's a difference between running:: and loading the library.

**Comment by gogonzo** [comment]
It is a `runner` internal problem. I'll fix it soon to use `runner::runner`

**Comment by gogonzo** [comment]
Please use latest CRAN version - bug fix has been included in latest release
https://cran.r-project.org/web/packages/runner/index.html
