### ISSUE TITLE
Not working or bad example in docs

### ISSUE THREAD

**Issue by hedgeye-mbarr** [gogonzo/runner#77]
library(runner)

# sample data
x <- cumsum(rnorm(10))
data <- data.frame(
  date = Sys.Date() + cumsum(sample(1:3, 10, replace = TRUE)), # unequally spaced time series, 
  y = 3 * x + rnorm(10), 
  x = cumsum(rnorm(10))
)

# solution
data$pred <- runner(
  data,
  na_pad = TRUE,
  lag = 1,
  k = 4,
  f = function(data) {
    predict(
      lm(y ~ x, data = data)
    )[nrow(data)]
  }
)
lm( y ~ x, data = data[1:4,])  %>% predict(., newdata = data[5,]) == data[5, "pred"]

**Comment by gogonzo** [comment]
Thanks for feedback. This might be wrong example. `runner` is working properly but example does not predict "future" observation but have lagged prediction (I'd rather call it smoothing).

```r
data$pred <- runner(
    data,
    na_pad = TRUE,
    k = 5,
    f = function(data) {
        predict(
            lm(y ~ x, data = data[1:4, ]),
            tail(data, 1)
        )
    }
)

lm(y ~ x, data = data[1:4,]) %>% predict(., newdata = data[5,]) == data[5, "pred"]

```

I think I will fix the example then.

**Comment by hedgeye-mbarr** [comment]
Thanks for clarifying. I was confused as to the intended functionality due to this description of the example in the vignette. I would just suggest rephrasing this:

“Prediction on current day based on preceding 2-weeks regression”
