### ISSUE TITLE
Parallelization with big datasets

### ISSUE THREAD

**Issue by JacopoVanoli** [gogonzo/runner#81]
Hello @gogonzo ,

I am working on environmental exposure data and I need to produce averages of a single exposure for different time windows and at selected samples of dates. I have pollutants data available at individual level for a very long time, i.e. daily levels for 11 years, and several dozen of thousands of individuals.

To achieve this I looked into one of your [examples](https://cran.r-project.org/web/packages/runner/vignettes/runner_examples.html), specifically the last one, i.e.  _Aggregating values from another data.frame in grouped_df_.

As you can see below I have prepared a working example based on your code using _n_ individuals.
The `exp_series` dataset contains my toy daily exposure data for each individual (4017 is the number of days between 01/01/2005 to 31/12/2015) and the `sample_dates` dataset contains a sample of dates for each subject within that follow-up time from which I want to extract the average exposure of the prior 365 days with 1 day lag. 
I decided to run the simulation in 2 separate conditions, _n_ =10k (k=1000) and _n_ =100k, and number of sample dates fixed at 10k. 

System specifications of the machine I used to run the simulation on:

> Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz, 2301 Mhz, 6 Core(s), 12 Logical Processor(s) with Windows 10. 

### Working example:
```
library(parallel)
library(runner)

#Sample data
set.seed(111)
exp_series <- data.frame(
  id = as.character(rep(x=1:100000, each=4017)), #change x= 10000
  date = rep(seq(as.Date('2005-01-01'),
                 as.Date('2015-12-31'), by = 'day'),times=100000),#change times= 10000
  exp = rep(rnorm(n=100000, mean=10, sd=5),times=4017)#change n= 10000
)


sample_dates <- data.frame(
  Event_id = as.character(replicate(n=10000,
sample(x=1:100000,size = 1,replace = TRUE))), #change x=10000
  Event_date = sample(
    seq(as.Date('2005-01-01'),
        as.Date('2015-12-31'), by = 'day'),
    size =10000,replace = TRUE)
)


You can see below the results of my simulation in terms of time and warnings produced.  

#Uncomment when running parallelized code
#numCores <- detectCores()
#cl <- makeCluster(numCores)


#Exposure summaries dataset
system.time(exposure_summaries <- sample_dates %>%
  group_by(Event_id) %>%
  mutate(
    mean = runner(
      x = exp_series[exp_series$id ==  Event_id[1],], 
      k = "365 days", 
      lag = "1 days",
      idx =exp_series$date[exp_series$id == Event_id[1]],
      at = Event_date,
      f = function(x) {mean(x$exp)},
      na_pad=FALSE#,
     #Uncomment when running parallelized code
     #cl = cl 
    )
  )
)

#Uncomment when running parallelized code
#stopCluster(cl)
```
### Results on my machine:
```
##################
#Results from testing: serial vs parallelization

###
#exp_series with 10k rows

#YES parallelization:
#user   system  elapsed 
#12267.75  1409.73 13952.49

#NO parallelization:
#user  system elapsed 
#9678.58  269.07 9950.24 
###


###
#exp_series with 100k rows

#YES parallelization:
# user   system  elapsed 
# 99763.36   3943.07 106903.92 

#NO parallelization:
#user  system elapsed 
# Warning: stack imbalance in '==', 96 then 95
# Warning: stack imbalance in '[', 93 then 92
# Warning: stack imbalance in 'NextMethod', 84 then 83
# Warning: stack imbalance in '[', 68 then 67
# user   system  elapsed 
# 96603.98  2732.89 99313.77
###
```

I was not able to properly find the reason of the warnings above for the 100k simulation but they did not appear when running the parallelized code.
The interesting thing for me is that parallelized the code does not seem to speed up the running time, rather it does slow it down! I know that this usually happens when the amount of work to be processed is not big enough, but this seems to be big enough.

Might the problem be linked to the fact that, in this case, to speed up the code I would ideally have to parallelize the process by groups. Meaning, using a core to compute the averages within each individual in parallel. On my machine that would allow to work on 24 individuals at the same time.
 
What do you think about this? I **really** need to speed this up!!

**Comment by gogonzo** [comment]
Hi @JacopoVanoli , thank you for using `runner` and for your feedback. 

Parallelization does not guarantee any gains in speed. It always depends on a type of the task. `runnner` applies window functio in parallel. So if the window is small and computation within a window is not complex then parallelization is not really a good choice. This happens because managing parallel nodes costs significant amount or resources.

I would rather try to focus on sending group-computation to the parallel nodes.

Also joining data inside of the groups looks demanding - worth maybe a merging to one data.frame before?
```
exp_series[exp_series$id ==  Event_id[1],]
```

Regards,
DK
