### ISSUE TITLE
comparison (1) is possible only for atomic and list types

### ISSUE THREAD

**Issue by MislavSag** [gogonzo/runner#84]
I have a little bit complex problem that is hard to reproduce.

In my package finfeatures, I use runner a lot https://github.com/MislavSag/finfeatures

Everything works as expected.

Than, I have wrote plumber API endpoint that uses functions from my finfeatures package.

When I try to execute endpoint (send POST request), I get an error:
```
Error in x[[1]] == as.name(\"runner\"): comparison (1) is possible only for atomic and list types
```
This same function works locally, but doesn't work through plumber requests.

I have found the problem is in this part: https://github.com/gogonzo/runner/search?q=x%5B%5B1%5D%5D+%3D%3D+as.name%28%22runner%22%29

My code that uses runner https://github.com/MislavSag/finfeatures/blob/main/R/RollingGeneric.R

Do you have any idea what could be the problem?

**Comment by gogonzo** [comment]
Thank you @MislavSag for this. This causes a lot of unexpected problems in the community, I should have design some stuff better. I'll need fix it finally. I should have some spare time today, but otherwise I'll be able to go back to this in one month (vacations)

**Comment by MislavSag** [comment]
It would be great if you can fix it this day. But even if not I will find some workaround.

**Comment by gogonzo** [comment]
Closing - fixed version on CRAN
