### ISSUE TITLE
x[[1]] == as.name("runner")

### ISSUE THREAD

**Issue by Steviey** [gogonzo/runner#88]
Is there an explanation for the message?

```
test        <-do.call(runner,list(x=df,k=daSize,f=custom_fun_runner,simplify=FALSE,na_pad=TRUE))
View(test)
stop()

Error in x[[1]] == as.name("runner") : 
  comparison (1) is possible only for atomic and list types
     x

```

**Comment by gogonzo** [comment]
Hi @Steviey ,
I guess it's a duplicate of https://github.com/gogonzo/runner/issues/87
Which version of runner you are using? If lower than 0.4.2 please update

**Comment by Steviey** [comment]
Didn't update all systems... got it.
