### ISSUE TITLE
Only use full windows.

### ISSUE THREAD

**Issue by Steviey** [gogonzo/runner#90]
Unfortunately I don't understand the docs... 

https://mran.microsoft.com/snapshot/2020-03-10/web/packages/runner/vignettes/apply_any_r_function.html

I drank some beers, but it does not help.

How can I tell runner to only use full windows defined by k?

**Comment by gogonzo** [comment]
Hi @Steviey can you explain me what "full" windows means?

**Comment by Steviey** [comment]
Sorry, it seems runner is delivering always full windows/datasets (nrow=10).
Must be something else in my prod-code.

```
library(runner)

doThatShit<-function(df){
    print(nrow(df))
}

dfOrig<-data.frame(a=seq(1,100,1),b=seq(1,100,1))

test<-do.call(runner,list(x=dfOrig,k=10,f=doThatShit,simplify=FALSE,na_pad=TRUE))
```

**Comment by gogonzo** [comment]
Hi @Steviey 
Please go to a better documentation, this might be more clear https://gogonzo.github.io/runner/articles/apply_any_r_function.html  
The documentation from the mran is little older.

Anyway, can you provide an abstract example and what you expect from runner? What do you mean by full window?
You'd like to return a list where each element will have `k`-long window?

**Comment by gogonzo** [comment]
Ok, @Steviey 
Please close if you're fine 👍
